import { NAIRA } from '../utils/helpers';

const en = {
  tagline: 'Healthcare payments, simplified.',
  welcomeBody: 'Pay hospital bills, manage family health expenses, and track your spending — all in one place.',
  getStarted: 'Get started',
  terms: 'By continuing you agree to our Terms & Privacy Policy',
  phoneTitle: 'Enter your number',
  phoneHelper: "We'll send you a one-time code to verify.",
  phoneLabel: 'Phone number',
  sendCode: 'Send code',
  phoneError: 'Please enter a valid 10-digit number.',
  otpTitle: 'Enter the code',
  otpHelper: 'We sent a 6-digit code to ',
  demoCorrect: '✓ Fill correct code',
  demoWrong: '✕ Fill wrong code',
  resendLabel: (n: number) => n > 0 ? `Resend in ${n}s` : 'Resend code',
  changeNumber: 'Change number',
  otpWrongMsg: 'Incorrect code. Please try again.',
  profileTitle: 'Tell us about you',
  fullName: 'Full name', dob: 'Date of birth', dobHelper: 'Must be 18+', emailOpt: 'Email (optional)',
  continue: 'Continue',
  lockTitle: 'Set your app PIN', lockHelper: 'Choose a 4-digit PIN to protect your account.',
  setPinLabel: 'Enter your PIN', confirmPinLabel: 'Confirm your PIN',
  pinMismatchMsg: "PINs don't match. Please try again.",
  useBiometric: 'Enable Face / Fingerprint instead',
  linkTitle: 'Link your WelliRecord',
  linkDoesLabel: 'What this does:', linkDoes: 'Automatically imports your hospital bills from linked facilities.',
  linkNotLabel: "What it doesn't do:", linkNot: 'Share your medical records or diagnoses.',
  linkNow: 'Link my WelliRecord', linkedSuccessMsg: '✓ WelliRecord linked successfully.', skipForNow: 'Skip for now',
  walletIntroTitle: 'Create your WelliPay Wallet',
  walletIntroBody: 'Top up your wallet and pay bills instantly — no card details needed each time.',
  createWallet: 'Create my wallet',
  summaryKicker: 'Total outstanding', nextDueKicker: 'Next due', due: 'Due', payNow: 'Pay now',
  walletKicker: 'Wallet balance', recentBills: 'Recent bills', noBillsYet: 'No bills yet. Add one below.',
  addBill: '+ Add a bill',
  notifsTitle: 'Notifications', noNotifs: "You're all caught up.",
  billsTitle: 'Bills', filterAll: 'All', filterUnpaid: 'Due', filterPaid: 'Paid',
  noBillsFilter: 'No bills match this filter.',
  addBillTitle: 'Add a bill', scanFrameHelp: 'Align the QR code on your bill within the frame',
  enterCodeInstead: 'Enter bill code instead', billCode: 'Bill code',
  demoValid: 'Demo: Valid code', demoExpired: 'Demo: Expired code', demoAlready: 'Demo: Already added',
  billNotFound: 'Bill not found. Please check the code.',
  billExpired: 'This bill code has expired.', billAlreadyAdded: 'This bill is already in your account.',
  billAdded: 'Bill added!', voidBanner: 'This bill has been cancelled by the facility.',
  showAllLines: (n: number) => `Show all ${n} items`, collapseLines: 'Show less',
  payerSplit: 'Insurance split', youPay: 'You pay', hmoPays: 'HMO pays',
  billTotal: 'Bill total', total: 'Total', shareStatement: 'Share statement',
  reportProblem: 'Report a problem', viewReceipt: 'View receipt',
  billChangedMsg: 'This bill was updated by the facility.',
  amountTitle: 'Choose amount', payFull: 'Pay full amount', payPart: 'Pay part amount',
  minPartHelper: (amt: string) => `Minimum part payment: ${amt}`,
  balanceAfterLabel: (rem: string) => `Remaining after this payment: ${rem}`,
  amountTooLow: (min: string) => `Minimum amount is ${min}`, amountTooHigh: 'Amount cannot exceed the balance due.',
  methodTitle: 'Choose payment method',
  payWithWallet: 'Pay from Wallet', payWithWalletSub: (bal: string) => `Balance: ${bal}`,
  insufficientWallet: 'Not enough balance — ',
  payWithCard: 'Debit / Credit card', payWithCardSub: 'Visa, Mastercard, Verve',
  payWithTransfer: 'Bank transfer', payWithTransferSub: 'Transfer to a one-time account number',
  paymentCancelledMsg: 'Payment was cancelled. Choose a method to try again.',
  confirmTitle: 'Confirm payment', youArePaying: 'You are paying', method: 'Method', totalCharge: 'Total charge',
  confirmBtn: 'Confirm & enter PIN', cancel: 'Cancel',
  confirmPinPrompt: 'Enter your 4-digit PIN', confirmFailedMsg: 'Wrong PIN. Please try again.', tryAgain: 'Try again',
  openingSecure: 'Opening secure payment…', checkingPayment: 'Checking your payment…',
  securePaymentKicker: 'SECURE PAYMENT', cardNumberLabel: 'Card number', expiryLabel: 'Expiry', cvvLabel: 'CVV',
  demoThreeDS: 'Demo: 3DS step', demoDecline: 'Demo: Decline card',
  transferTitle: 'Bank transfer',
  transferInstruction: 'Transfer the exact amount to the account below. Your payment will be confirmed automatically.',
  bankName: 'Bank', accountNumber: 'Account number', accountName: 'Account name',
  amount: 'Amount', copy: 'Copy', expiresIn: 'Expires in',
  transferNote: 'This account number is valid for one payment only. Do not reuse it.',
  iHavePaid: "I've sent the money", chooseAnotherMethod: 'Choose a different method',
  transferExpiredMsg: 'This account number has expired.', getNewAccount: 'Get a new account number',
  pendingMsg: 'Your payment is being confirmed. This usually takes a few minutes.',
  demoResolveSuccess: 'Demo: Mark successful', demoResolveReview: 'Demo: Under review',
  successHeading: 'Payment successful', stillToPay: (rem: string) => `Balance remaining: ${rem}`,
  payBalanceBtn: 'Pay remaining balance', backToBills: 'Back to bills',
  failedHeading: 'Payment failed',
  failReason: { declined:'Your card was declined.', expired:'Session expired.', default:'Something went wrong.' },
  useAnotherMethod: 'Use a different method',
  expiredMsg: 'Your session expired. Please try again.',
  underReviewMsg: "Your payment is being reviewed. We'll notify you when it's confirmed.",
  contactSupport: 'Contact support', receiptTitle: 'Receipt',
  facilityLabel: 'Facility', personLabel: 'Patient', methodLabel2: 'Payment method',
  amountPaid: 'Amount paid', balanceLabel: 'Remaining balance',
  share: 'Share', download: 'Download',
  historyTitle: 'Payments', thisMonth: 'This month', noPaymentsYet: 'No payments yet.',
  reportTitle: 'Report a problem', reportCategoryLabel: "What's the issue?",
  cat_wrongAmt: 'Wrong amount', cat_alreadyPaid: 'Already paid', cat_duplicate: 'Duplicate charge', cat_other: 'Something else',
  reportDescLabel: 'Describe the issue', reportDescPlaceholder: 'Tell us what happened…',
  reportSubmit: 'Submit report', reportSubmittedMsg: "Report submitted. We'll be in touch.",
  reportdetailTitle: 'Report status', ticketLabel: 'Ticket no.', statusLabel: 'Status',
  reportFollowupNote: 'A WelliPay agent will contact you within 1 business day.', underReviewStatus: 'Under review',
  walletTitle: 'Wallet', topUpBtn: 'Top up', autoPayLabel: 'Auto-pay bills',
  autoPaySub: 'Automatically pay bills from wallet when due.', walletActivity: 'Activity', noWalletActivity: 'No transactions yet.',
  topup_title: 'Top up wallet', savings_topup_title: 'Contribute to savings', customAmountLabel: 'Or enter custom amount',
  topupPresets: ['₦5,000', '₦10,000', '₦20,000', '₦50,000'],
  insightsTitle: 'Insights', scopeMe: 'Just me', scopeFamily: 'Whole family',
  spendingKicker: 'Spending — last 4 months', familySpendKicker: 'Spending by person',
  upcomingKicker: 'Upcoming expenses', noUpcoming: 'No upcoming bills.', manageReminders: 'Manage reminders',
  insuranceKicker: 'Insurance utilisation', hmoPaidLabel: 'HMO:', youPaidLabel: 'You:',
  savingsKicker: 'Savings goal', contributeBtn: 'Contribute',
  financingKicker: 'Financing obligations', nextInstallment: 'Next installment:', payInstallmentBtn: 'Pay next installment',
  noPlans: 'No active financing plans.',
  peopleTitle: 'People', addPerson: '+ Add a person', addDepTitle: 'Add a person',
  depNameLabel: 'Full name', depRelationLabel: 'Relationship', depDobLabel: 'Date of birth',
  depSave: 'Save', depNameRequired: 'Please enter a name.',
  rel_child: 'Child', rel_spouse: 'Spouse', rel_parent: 'Parent', rel_other: 'Other',
  profile2Title: 'Profile',
  settingsMenu: ['People','Security','Privacy','Notifications','Language','Help','Contact us','Legal'],
  deleteAccountLabel: 'Delete account', logOut: 'Log out',
  securityTitle: 'Security', biometricLabel: 'Face / Fingerprint unlock', biometricSub: 'Use biometrics to open the app.',
  changePinLabel: 'Change PIN',
  privacyTitle: 'Privacy & consent', hmoShareLabel: 'Share bills with HMO', hmoShareSub: 'Allow your insurer to view bill line items.',
  marketingLabel: 'Marketing messages', marketingSub: 'Receive offers and promotions from WelliPay.',
  notifprefsTitle: 'Notification preferences', billAlertsLabel: 'New bill alerts', receiptsLabel: 'Payment receipts', promoLabel: 'Promotions',
  languageTitle: 'Language', helpTitle: 'Help centre', contactTitle: 'Contact us',
  callSupport: 'Call us', whatsappSupport: 'WhatsApp', emailSupport: 'Email',
  legalTitle: 'Legal', termsLink: 'Terms of service', privacyLink: 'Privacy policy', refundLink: 'Refund policy',
  deleteTitle: 'Delete account',
  deleteWarning: 'Deleting your account will permanently remove all your data, including bills, payment history, and wallet balance. This cannot be undone.',
  deleteFinalWarning: 'Are you absolutely sure? This action is irreversible.',
  deleteConfirmBtn: 'I understand — delete my account', deleteFinalBtn: 'Yes, delete permanently',
  deleteCancel: 'Keep my account', deleteDoneMsg: 'Your account has been deleted.',
  tabHome: 'Home', tabBills: 'Bills', tabWallet: 'Wallet', tabInsights: 'Insights', tabPay: 'Payments', tabProfile: 'Profile',
  people: 'Household', copiedMsg: 'Copied!',
  payCtaPartial: (bal: string) => `Pay ${bal}`, billNo: 'Bill no.', dueLabel: 'Due',
  runAutoPayLabel: (b: string) => `Run auto-pay now (${b})`, autoPayRanMsg: (b: string) => `Auto-pay ran: ${b} deducted.`,
  // -- healthcare & insurance
  hmoTitle: 'Health Insurance & HMO',
  hmoSub: 'Active coverage and policy benefits',
  addHmoBtn: '+ Add HMO Card',
  addHmoTitle: 'Add HMO Policy',
  providerLabel: 'HMO Provider',
  policyNoLabel: 'Policy / Enrollee Number',
  planTierLabel: 'Plan Tier',
  coPayLabel: 'Patient Co-Pay',
  annualLimitLabel: 'Annual Benefit Limit',
  usedAmountLabel: 'Used this year',
  remainingLimit: 'Remaining',
  preAuthTitle: 'Pre-Authorizations',
  requestPreAuthBtn: 'Request Pre-Auth',
  newPreAuthTitle: 'New Pre-Authorization',
  preAuthStatusApproved: 'Approved',
  preAuthStatusReview: 'In Review',
  preAuthStatusDeclined: 'Declined',
  applyHmoBtn: 'Apply HMO Co-Pay',
  hmoAppliedMsg: 'HMO coverage applied successfully.',
  welliRecordSyncTitle: 'WelliRecord EMR Sync',
  syncNowBtn: 'Sync latest hospital bills',
  syncingText: 'Connecting to hospital EMR…',
  syncSuccessText: 'Hospital billing ledgers are up to date.',
  facilitiesTitle: 'Partner Hospitals',
  facilitiesSub: 'Direct bank settlement & verified billing',
  searchFacilities: 'Search hospital, clinic, or location',
  directSettlementLabel: 'Direct Bank Settlement',
  acceptedHmosLabel: 'Accepted Insurance Plans',
  emergencyLine: 'Emergency Hotline',
  healthcareSectionTitle: 'Healthcare & Coverage',
  linkedHospitalsCount: (n: number) => `${n} Hospitals Linked`,

};

const pcm: typeof en = {
  ...en,
  tagline: 'Hospital bills, e don easy.',
  welcomeBody: 'Pay your hospital bill, manage your family health money, and see how you dey spend — everything dey one place.',
  getStarted: 'Make we start',
  terms: 'As you continue, you don agree to our Terms & Privacy Policy',
  phoneHelper: 'We go send you one code to verify.',
  sendCode: 'Send code', phoneError: 'Abeg enter correct 10-digit number.',
  otpHelper: 'We don send 6-digit code go ', otpWrongMsg: 'Code no correct. Try again.',
  profileTitle: 'Tell us about yourself', dobHelper: 'You must reach 18 years',
  lockTitle: 'Set your PIN', lockHelper: 'Choose 4-digit PIN to protect your account.',
  pinMismatchMsg: 'PIN no match. Try again.', useBiometric: 'Use Face/Fingerprint instead',
  linkDoesLabel: 'Wetin e go do:', linkNotLabel: 'Wetin e no go do:',
  linkDoes: 'E go pull your hospital bills automatically from linked facilities.',
  linkNot: 'E no go share your medical records.',
  linkedSuccessMsg: '✓ WelliRecord don link.', createWallet: 'Create my wallet',
  walletIntroBody: 'Top up your wallet and pay hospital bills sharp sharp — no need enter card every time.',
  summaryKicker: 'Total wey you owe', noBillsYet: 'No bills yet. Add one below.',
  addBill: '+ Add bill', scanFrameHelp: 'Put the QR code inside the frame',
  billExpired: 'This bill code don expire.', billAlreadyAdded: 'This bill don already dey your account.',
  billAdded: 'Bill don add!', voidBanner: 'This bill don cancel by the hospital.',
  billChangedMsg: 'Hospital don update this bill.', payPart: 'Pay part',
  balanceAfterLabel: (rem: string) => `Wey go remain: ${rem}`,
  amountTooLow: (min: string) => `Minimum amount na ${min}`,
  amountTooHigh: 'Amount no fit pass the balance.', methodTitle: 'Choose how to pay',
  insufficientWallet: 'Balance no enough — ',
  payWithTransferSub: 'Transfer to one-time account number',
  paymentCancelledMsg: 'Payment cancel. Choose method to try again.',
  youArePaying: 'You wan pay', confirmBtn: 'Confirm & enter PIN',
  confirmPinPrompt: 'Enter your 4-digit PIN', confirmFailedMsg: 'Wrong PIN. Try again.',
  openingSecure: 'Opening secure payment…', checkingPayment: 'Checking your payment…',
  transferInstruction: 'Transfer the exact amount go the account below. Your payment go confirm automatically.',
  expiresIn: 'E go expire in', transferNote: 'This account number na for one payment only. No use am again.',
  iHavePaid: 'I don send the money', chooseAnotherMethod: 'Choose different method',
  transferExpiredMsg: 'This account number don expire.', getNewAccount: 'Get new account number',
  pendingMsg: 'Your payment dey verify. E go take small time.',
  successHeading: 'Payment successful', stillToPay: (rem: string) => `Balance wey remain: ${rem}`,
  failedHeading: 'Payment no work',
  failReason: { declined:'Your card don decline.', expired:'Session don expire.', default:'Something happen. Try again.' },
  expiredMsg: 'Your session don expire. Try again.',
  underReviewMsg: 'We dey check your payment. We go notify you when e confirm.',
  topup_title: 'Top up wallet', savings_topup_title: 'Contribute to savings',
  customAmountLabel: 'Or enter your own amount',
  spendingKicker: 'Spending — last 4 months', insuranceKicker: 'Insurance usage',
  savingsKicker: 'Savings goal', financingKicker: 'Financing plans',
  noPlans: 'No active plans.',
  depNameRequired: 'Abeg enter name.',
  deleteWarning: 'If you delete your account, all your data go disappear — bills, payment history, wallet balance. We no fit bring am back.',
  deleteFinalWarning: 'You sure? This one no fit undo.',
  deleteConfirmBtn: 'I understand — delete my account', deleteFinalBtn: 'Yes, delete permanently',
  deleteCancel: 'Keep my account', deleteDoneMsg: 'Your account don delete.',
  autoPaySub: 'Pay bills from wallet automatically when dem due.', noWalletActivity: 'No transactions yet.',
  runAutoPayLabel: (b: string) => `Run auto-pay now (${b})`, autoPayRanMsg: (b: string) => `Auto-pay run: ${b} don comot.`,
  // -- healthcare & insurance
  hmoTitle: 'Health Insurance & HMO',
  hmoSub: 'Your HMO plan and benefits',
  addHmoBtn: '+ Add HMO Card',
  addHmoTitle: 'Add HMO Policy',
  providerLabel: 'HMO Company',
  policyNoLabel: 'Policy / Card Number',
  planTierLabel: 'Plan Type',
  coPayLabel: 'Your Portion (Co-Pay)',
  annualLimitLabel: 'Total Money for Year',
  usedAmountLabel: 'Wey you don spend',
  remainingLimit: 'Money wey remain',
  preAuthTitle: 'Prior Approvals (Pre-Auth)',
  requestPreAuthBtn: 'Ask for Approval',
  newPreAuthTitle: 'Ask for New Approval',
  preAuthStatusApproved: 'Don Approve',
  preAuthStatusReview: 'Dem Dey Check Am',
  preAuthStatusDeclined: 'No Agree',
  applyHmoBtn: 'Use HMO Pay',
  hmoAppliedMsg: 'HMO coverage don join your bill.',
  welliRecordSyncTitle: 'WelliRecord EMR Connect',
  syncNowBtn: 'Pull latest bills from hospital',
  syncingText: 'Dey connect to hospital computer…',
  syncSuccessText: 'All your hospital bills don sync.',
  facilitiesTitle: 'Partner Hospitals',
  facilitiesSub: 'Direct bank payment & clear bills',
  searchFacilities: 'Find hospital or clinic',
  directSettlementLabel: 'Direct Bank Payment',
  acceptedHmosLabel: 'Insurance Wey Dem Dey Take',
  emergencyLine: 'Emergency Phone',
  healthcareSectionTitle: 'Healthcare & Insurance',
  linkedHospitalsCount: (n: number) => `${n} Hospitals Don Connect`,

};

export type CopyDict = typeof en;
export const COPY: Record<string, CopyDict> = { en, pcm };
